remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme # add this line to the plugins list if you already have one
title: Speech Behavior and Science Lab
description: Graduate Institute of Linguistics, National Taiwan University
canonical_url: https://sbslab.linguistics.ntu.edu.tw
